# src/reports/report_common.py

import html
import os
from datetime import datetime


def safe(text):
    return html.escape(str(text))


def get_report_output_folder():
    return os.path.join(
        os.path.expanduser("~"),
        "Desktop",
        "WARPSimLab",
        "Reports",
    )


def safe_report_id(report_id):
    return "".join(
        ch if ch.isalnum() or ch in {"-", "_"} else "_"
        for ch in str(report_id)
    )


def relative_asset_path(image_path, output_folder):
    if not image_path:
        return None

    try:
        return os.path.relpath(image_path, start=output_folder)
    except (TypeError, ValueError):
        return image_path


def render_report_header(report_data, *, title=None, market_wording="simulated market conditions"):
    report_title = title or report_data.report_metadata.get(
        "Report Title",
        "WARPSimLab Report",
    )

    return f"""
<section class="report-header">
    <h1>
        <span class="brand-name">WARPSimLab</span> {safe(report_title)}
    </h1>
    <div class="brand-website">warpsimlab.org</div>
    <div class="metadata-grid">
        <div><strong>Generated:</strong> {safe(report_data.report_metadata.get("Generated Timestamp", "N/A"))}</div>
        <div><strong>Projection Period:</strong> {safe(report_data.report_metadata.get("Projection Period", "N/A"))}</div>
        <div><strong>Report Basis:</strong> {safe(report_data.report_metadata.get("Report Basis", "N/A"))}</div>
        <div><strong>Report ID:</strong> {safe(report_data.report_metadata.get("Report ID", "N/A"))}</div>
    </div>
    <div class="disclaimer">
        <p>This report is intended solely for educational purposes.</p>
        <p>It is not financial, investment, tax, legal, retirement, or other professional advice.</p>
        <p>All results are generated from user-provided assumptions and {safe(market_wording)}.</p>
    </div>
</section>
"""


def render_footer():
    return f"""
<div class="footer">
    Generated by WARPSimLab on {safe(datetime.now().isoformat(timespec="seconds"))}.
</div>
"""


def render_base_css():
    return """
body {
    font-family: Arial, sans-serif;
    margin: 0;
    color: #222;
    line-height: 1.4;
    background: #fff;
}

.report-page {
    max-width: 920px;
    margin: 34px auto;
}

.report-header {
    border-top: 6px solid #2e7d32;
    padding-top: 12px;
}

.brand-name {
    color: #2e7d32;
}

.brand-website {
    color: #666;
    font-size: 14px;
    margin-top: -4px;
    margin-bottom: 12px;
}

h1 {
    margin: 0 0 10px 0;
    font-size: 30px;
}

h2 {
    margin-top: 34px;
    padding-bottom: 6px;
    border-bottom: 2px solid #ddd;
    font-size: 22px;
}

h3 {
    margin-top: 0;
    margin-bottom: 6px;
    font-size: 17px;
}

section {
    margin-bottom: 28px;
    page-break-inside: avoid;
}

.metadata-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(260px, 1fr));
    gap: 6px 24px;
    margin: 10px 0 14px 0;
    font-size: 14px;
}

.disclaimer {
    border: 1px solid #bbb;
    background: #f8f8f8;
    padding: 10px 12px;
    max-width: 900px;
    font-size: 14px;
}

.disclaimer p {
    margin: 4px 0;
}

.section-intro {
    max-width: 900px;
    color: #444;
    margin-top: 0;
}

.card-grid {
    display: grid;
    gap: 16px;
    margin-top: 14px;
}

.three-col {
    grid-template-columns: repeat(3, minmax(180px, 1fr));
}

.two-col {
    grid-template-columns: repeat(2, minmax(260px, 1fr));
}

.summary-card,
.explanation-card,
.placeholder-card,
.plot-card {
    border: 1px solid #ccc;
    background: #fafafa;
    padding: 14px;
    border-radius: 6px;
}

table {
    border-collapse: collapse;
    width: 100%;
}

.kv-table th,
.kv-table td {
    border-bottom: 1px solid #ddd;
    padding: 6px 4px;
    text-align: left;
    vertical-align: top;
}

.kv-table th {
    width: 58%;
    color: #333;
}

.kv-table td {
    text-align: right;
}

.emphasis-row th,
.emphasis-row td {
    font-weight: bold;
    background: #f2f2f2;
}

.wide-table {
    margin-top: 14px;
    font-size: 14px;
}

.wide-table th,
.wide-table td {
    border: 1px solid #ccc;
    padding: 7px 8px;
    text-align: left;
    vertical-align: top;
}

.wide-table thead th {
    background: #f0f0f0;
}

.negative {
    color: #b00020;
    font-weight: bold;
}

.highlight-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 14px;
    margin-top: 14px;
}

.highlight-card {
    border: 1px solid #bbb;
    background: #f5f7fa;
    padding: 16px;
    border-radius: 7px;
    border-top: 5px solid #2e7d32;
}

.highlight-card.negative-risk {
    border-top-color: #b00020;
}

.highlight-label {
    font-size: 16px;
    color: #2e7d32;
    font-weight: 600;
    margin-bottom: 8px;
}

.highlight-card.negative-risk .highlight-label {
    color: #b00020;
}

.highlight-value {
    font-size: 20px;
    font-weight: bold;
    color: #111;
}

.plot-card {
    margin-top: 14px;
}

.plot-card img {
    width: 70%;
    max-width: 700px;
    height: auto;
    display: block;
    margin: 10px auto 0 auto;
}

.plot-stack {
    display: block;
    max-width: 1200px;
    margin-top: 14px;
}

.warnings {
    border: 1px solid #d6b656;
    background: #fff8dd;
    padding: 12px 12px 12px 30px;
}

.footer {
    margin-top: 36px;
    color: #666;
    font-size: 13px;
}

@media print {
    body {
        margin: 0;
    }

    .report-page {
        max-width: 900px;
        margin: 22px auto;
        padding: 0;
    }

    .three-col {
        grid-template-columns: repeat(3, 1fr);
    }

    .two-col {
        grid-template-columns: repeat(2, 1fr);
    }

    .highlight-grid {
        grid-template-columns: repeat(3, 1fr);
    }

    .plot-card {
        page-break-inside: avoid;
        break-inside: avoid;
    }

    section {
        page-break-inside: avoid;
    }
}
"""