# gui_main.py

import tkinter as tk
from tkinter import ttk

import os
import getpass
from datetime import datetime
from pathlib import Path


# ------------------------------------------------------------------
# Editable home page text
# ------------------------------------------------------------------

HOME_TITLE = "Home"

INTRO_TEXT = (
    "WARPSimLab.\n\n"
    "WARPSimLab (the Wealth Analysis & Retirement Planning Simulator Lab) is an "
    "educational personal finance simulator designed to help users explore long-term "
    "financial trends, budgets, assets, and portfolio dynamics in a safe, interactive "
    "environment. This tool is not financial advice and is intended for learning and "
    "experimentation only.\n"
)

FIRST_USE_TEXT = (
    "New users: Accept the terms below, then select Start Tutorials.\n"
)

LEGAL_TEXT = (
    "------------------------------------------------------------------\n"
    "IMPORTANT LEGAL DISCLAIMER & TERMS OF USE\n"
    "------------------------------------------------------------------\n\n"

    "1) EDUCATIONAL USE ONLY\n"
    "This simulator is provided for educational and informational purposes only. "
    "It does not constitute financial, investment, tax, legal, or retirement advice. "
    "Use of this software does not create a professional or fiduciary relationship. "
    "This software is not intended to be used as a retirement planning tool or to "
    "determine investment allocations, withdrawal strategies, or financial decisions.\n\n"

    "2) HYPOTHETICAL RESULTS\n"
    "All results generated by this simulator are hypothetical and are based on "
    "user-supplied assumptions and simplified financial models. These models may "
    "omit relevant factors and may contain errors or limitations. Results are highly "
    "sensitive to user inputs and small changes may materially affect outcomes. "
    "Results are not predictions or guarantees of future performance.\n\n"

    "3) NO WARRANTIES\n"
    "This software is provided on an \"AS IS\" basis, without warranties of any kind, "
    "express or implied, including but not limited to the accuracy, completeness, "
    "or reliability of any calculations or outputs.\n\n"

    "4) LIMITATION OF LIABILITY\n"
    "By using this software, you assume all risks associated with its use. The creator "
    "shall not be liable for any financial losses, damages, or other consequences "
    "resulting from the use or misuse of this simulator.  The creator does not provide "
    "ongoing monitoring, updates tailored to your situation, or individualized "
    "financial guidance.\n\n"

    "5) PRIVACY\n"
    "Information entered into this simulator is processed locally on your computer "
    "and is not intentionally transmitted to the creator. This software may store a local "
    "record that you accepted these terms (including a timestamp and terms version) to "
    "avoid prompting you again.\n\n"

    "This software is released under the MIT License. See LICENSE.txt for full license terms.\n\n"

    "You should consult qualified financial, tax, or legal professionals before "
    "making decisions related to your personal finances."
)

class MainHomeFrame(ttk.Frame):
    def __init__(self, parent, title=HOME_TITLE, parent_gui=None, **kwargs):
        """
        parent_gui: reference to the main GUI class, used to enable/disable run buttons
        """
        super().__init__(parent, padding=10, **kwargs)
        self.title = title

        self.parent_gui = parent_gui
        self.legal_already_accepted = self._legal_acceptance_exists()

        self.acceptance_timestamp = None
        if self.legal_already_accepted:
            self.acceptance_timestamp = (
                self._read_legal_acceptance_timestamp()
            )

        self.agree_var = tk.BooleanVar(
            value=self.legal_already_accepted
        )

        self._build_fields()

        if self.legal_already_accepted:
            self._update_run_buttons(enabled=True)
            self._update_nav_buttons(enabled=True)

    def _build_fields(self):
        # Title
        ttk.Label(
            self,
            text=self.title,
            font=("Arial", 16, "bold")
        ).pack(anchor="w", pady=(0, 10))

        # Introduction text directly on the frame
        intro_label = ttk.Label(
            self,
            text=INTRO_TEXT,
            wraplength=800,  # adjust width as needed
            justify="left",
            font=("Arial", 12)
        )
        intro_label.pack(anchor="w", pady=(0, 10))

        if self.legal_already_accepted:
            if self.acceptance_timestamp:
                acceptance_text = (
                    "Terms of Use accepted on "
                    f"{self.acceptance_timestamp}"
                )
            else:
                acceptance_text = "Terms of Use previously accepted."

            ttk.Label(
                self,
                text=acceptance_text,
            ).pack(anchor="w", pady=(5, 5))

            ttk.Button(
                self,
                text="View Terms of Use",
                command=self._view_terms_of_use,
            ).pack(anchor="w", pady=(0, 10))

            self.tutorial_button = ttk.Button(
                self,
                text="Start Tutorials",
                command=self._open_tutorials,
            )
            self.tutorial_button.pack(anchor="w", pady=(10, 0))
            return

        first_use_label = ttk.Label(
            self,
            text=FIRST_USE_TEXT,
            wraplength=800,
            justify="left",
            font=("Arial", 12),
        )
        first_use_label.pack(anchor="w", pady=(0, 10))

        # Scrollable legal text
        container = ttk.Frame(self)
        container.pack(fill="both", expand=True, pady=(0, 10))

        scrollbar = ttk.Scrollbar(container, orient="vertical")
        scrollbar.pack(side="right", fill="y")

        text_widget = tk.Text(
            container,
            wrap="word",
            yscrollcommand=scrollbar.set,
            borderwidth=0,
            relief="flat",
            highlightthickness=0,
            height=12 
        )
        text_widget.pack(side="left", fill="both", expand=True)
        scrollbar.config(command=text_widget.yview)

        text_widget.insert("1.0", LEGAL_TEXT)
        text_widget.config(state="disabled")

        # Checkbox at bottom
        checkbox = tk.Checkbutton(
            self,
            text="I have read and accept the terms above",
            variable=self.agree_var,
            command=self._on_agree_changed
        )
        checkbox.pack(anchor="w", pady=(10, 0))

        self.tutorial_button = ttk.Button(
            self,
            text="Start Tutorials",
            command=self._open_tutorials,
            state="disabled",
        )
        self.tutorial_button.pack(anchor="w", pady=(10, 0))

        # Initially disable run buttons
        if self.parent_gui:
            self._update_run_buttons(enabled=False)
            self._update_nav_buttons(enabled=False)


    def _view_terms_of_use(self):
        """
        Display the current WARPSimLab Terms of Use.
        """
        dialog = tk.Toplevel(self)
        dialog.title("WARPSimLab Terms of Use")
        dialog.geometry("800x600")
        dialog.transient(self.winfo_toplevel())

        container = ttk.Frame(dialog, padding=10)
        container.pack(fill="both", expand=True)

        scrollbar = ttk.Scrollbar(
            container,
            orient="vertical",
        )
        scrollbar.pack(side="right", fill="y")

        text_widget = tk.Text(
            container,
            wrap="word",
            yscrollcommand=scrollbar.set,
            borderwidth=0,
            relief="flat",
            highlightthickness=0,
        )
        text_widget.pack(
            side="left",
            fill="both",
            expand=True,
        )

        scrollbar.config(command=text_widget.yview)

        text_widget.insert("1.0", LEGAL_TEXT)
        text_widget.config(state="disabled")

        ttk.Button(
            dialog,
            text="Close",
            command=dialog.destroy,
        ).pack(pady=(0, 10))


    def _open_tutorials(self):
        if not self.parent_gui:
            return

        self.parent_gui.edit_tutorial()


    def _on_agree_changed(self):
        if self.agree_var.get():
            self._record_legal_acceptance_once()

        if self.parent_gui:
            enabled = self.agree_var.get()
            self._update_run_buttons(enabled)
            self._update_nav_buttons(enabled)

            if enabled:
                self.parent_gui.edit_main_home()


    def _update_run_buttons(self, enabled):
        """Enable or disable the Results menu through the parent GUI policy."""
        if not self.parent_gui:
            return

        self.parent_gui.legal_accepted = enabled

        if hasattr(self.parent_gui, "_apply_mode_to_results_button"):
            self.parent_gui._apply_mode_to_results_button()


    def _update_nav_buttons(self, enabled):
        """Enable or disable main navigation through the parent GUI policy."""
        if hasattr(self, "tutorial_button"):
            self.tutorial_button.configure(
                state="normal" if enabled else "disabled"
            )

        if not self.parent_gui:
            return

        self.parent_gui.legal_accepted = enabled

        if hasattr(self.parent_gui, "_apply_mode_to_top_buttons"):
            self.parent_gui._apply_mode_to_top_buttons()


    def _record_legal_acceptance_once(self):
        """
        Record legal acceptance the first time it occurs on this machine.
        Fail silently if the file cannot be written.
        """
        try:
            target_dir = (
                Path.home()
                / "Desktop"
                / "WARPSimLab"
                / "Administration"
            )
            target_dir.mkdir(parents=True, exist_ok=True)

            log_file = target_dir / "legal_acceptance.log"

            # Only write if the file does not already exist
            if log_file.exists():
                return

            username = None
            try:
                username = getpass.getuser()
            except Exception:
                pass

            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            with open(log_file, "w", encoding="utf-8") as f:
                f.write("WARPSimLab Legal Acceptance Record\n")
                f.write("--------------------------------\n")
                f.write(f"Accepted on: {timestamp} (local time)\n")
                if username:
                    f.write(f"OS User: {username}\n")

        except Exception:
            # Intentionally fail silently
            pass


    def _read_legal_acceptance_timestamp(self):
        """
        Return the recorded legal acceptance timestamp, or None.
        """
        try:
            log_file = (
                Path.home()
                / "Desktop"
                / "WARPSimLab"
                / "Administration"
                / "legal_acceptance.log"
            )

            if not log_file.exists():
                return None

            with open(log_file, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("Accepted on:"):
                        return line[len("Accepted on:"):].strip()

        except Exception:
            pass

        return None


    def _legal_acceptance_exists(self):
        """
        Returns True if a prior legal acceptance record exists.
        """
        try:
            log_file = (
                Path.home()
                / "Desktop"
                / "WARPSimLab"
                / "Administration"
                / "legal_acceptance.log"
            )
            return log_file.exists()
        except Exception:
            return False
