from __future__ import annotations

import os
from types import SimpleNamespace

from src.warpsimlab.reports import report_common as mod


def make_report_data(**metadata):
    base = {
        "Generated Timestamp": "2026-01-01 12:00:00",
        "Projection Period": "2026-2031 (5 Years)",
        "Report Basis": "Raw Dollars",
        "Report ID": "test-report",
        "Report Title": "Test Report",
    }
    base.update(metadata)

    return SimpleNamespace(report_metadata=base)


def test_safe_escapes_html_and_converts_to_string():
    assert mod.safe("<script>x</script>") == "&lt;script&gt;x&lt;/script&gt;"
    assert mod.safe("Tom & Jerry") == "Tom &amp; Jerry"
    assert mod.safe(123) == "123"
    assert mod.safe(None) == "None"


def test_get_report_output_folder_uses_desktop_warpsimlab_reports(monkeypatch):
    monkeypatch.setattr(mod.os.path, "expanduser", lambda value: "/home/test-user")

    folder = mod.get_report_output_folder()

    assert folder == os.path.join(
        "/home/test-user",
        "Desktop",
        "WARPSimLab",
        "Reports",
    )


def test_safe_report_id_preserves_alnum_dash_and_underscore():
    assert mod.safe_report_id("abc-DEF_123") == "abc-DEF_123"


def test_safe_report_id_replaces_spaces_slashes_and_symbols():
    assert mod.safe_report_id("report id/with spaces!") == "report_id_with_spaces_"
    assert mod.safe_report_id("a:b*c?d") == "a_b_c_d"


def test_safe_report_id_converts_non_string_values():
    assert mod.safe_report_id(12345) == "12345"


def test_relative_asset_path_returns_none_for_empty_path():
    assert mod.relative_asset_path(None, "/tmp/reports") is None
    assert mod.relative_asset_path("", "/tmp/reports") is None


def test_relative_asset_path_returns_relative_path(tmp_path):
    output_folder = tmp_path / "reports"
    asset_folder = output_folder / "assets"
    asset_folder.mkdir(parents=True)

    image = asset_folder / "plot.png"
    image.write_text("fake", encoding="utf-8")

    assert mod.relative_asset_path(
        str(image),
        str(output_folder),
    ) == os.path.join("assets", "plot.png")


def test_relative_asset_path_returns_original_when_relpath_fails(monkeypatch):
    def raise_value_error(*args, **kwargs):
        raise ValueError("different drives")

    monkeypatch.setattr(mod.os.path, "relpath", raise_value_error)

    assert mod.relative_asset_path(
        "C:\\reports\\plot.png",
        "D:\\reports",
    ) == "C:\\reports\\plot.png"


def test_render_report_header_uses_metadata_title_and_escapes_values():
    report_data = make_report_data(
        **{
            "Generated Timestamp": "<bad timestamp>",
            "Projection Period": "2026-2031",
            "Report Basis": "Raw <Dollars>",
            "Report ID": "abc/123",
            "Report Title": "<Unsafe Title>",
        }
    )

    html = mod.render_report_header(report_data)

    assert "WARPSimLab" in html
    assert "warpsimlab.org" in html
    assert "&lt;Unsafe Title&gt;" in html
    assert "&lt;bad timestamp&gt;" in html
    assert "2026-2031" in html
    assert "Raw &lt;Dollars&gt;" in html
    assert "abc/123" in html
    assert "educational purposes" in html
    assert "not financial, investment, tax, legal, retirement, or other professional advice" in html


def test_render_report_header_title_argument_overrides_metadata_title():
    report_data = make_report_data(
        **{
            "Report Title": "Metadata Title",
        }
    )

    html = mod.render_report_header(
        report_data,
        title="Explicit Title",
    )

    assert "Explicit Title" in html
    assert "Metadata Title" not in html


def test_render_report_header_escapes_market_wording():
    report_data = make_report_data()

    html = mod.render_report_header(
        report_data,
        title="Report",
        market_wording="<unsafe market wording>",
    )

    assert "&lt;unsafe market wording&gt;" in html


def test_render_report_header_uses_na_for_missing_metadata():
    report_data = SimpleNamespace(report_metadata={})

    html = mod.render_report_header(report_data)

    assert "WARPSimLab Report" in html
    assert "<strong>Generated:</strong> N/A" in html
    assert "<strong>Projection Period:</strong> N/A" in html
    assert "<strong>Report Basis:</strong> N/A" in html
    assert "<strong>Report ID:</strong> N/A" in html


def test_render_footer_contains_brand_and_iso_timestamp(monkeypatch):
    class FakeDateTime:
        @classmethod
        def now(cls):
            return cls()

        def isoformat(self, timespec="seconds"):
            assert timespec == "seconds"
            return "2026-01-01T12:34:56"

    monkeypatch.setattr(mod, "datetime", FakeDateTime)

    html = mod.render_footer()

    assert "Generated by WARPSimLab on 2026-01-01T12:34:56." in html


def test_render_base_css_contains_shared_report_classes():
    css = mod.render_base_css()

    assert "body {" in css
    assert ".report-page" in css
    assert ".report-header" in css
    assert ".metadata-grid" in css
    assert ".disclaimer" in css
    assert ".summary-card" in css
    assert ".plot-card" in css
    assert ".highlight-grid" in css
    assert ".warnings" in css
    assert "@media print" in css